### ISSUE TITLE
On changing store, search is appearing of earlier store

### ISSUE THREAD

**Issue by Pragyad07** [hotwax/inventory-count#126] opened 2022-12-13 13:27 UTC
## Current behavior

The user login in one instance(demo-oms), searches for the product, and then logout. Now the user login into another instance(dev-hc), still the search is showing the same product that was searched earlier in demo-oms instance.

https://user-images.githubusercontent.com/64180958/207332320-1bcac9a1-668f-4466-a41e-51297ab2569a.mov

## Expected behavior
User login in one instance, searches for the product, and logout. Further login into other instances, search should be clear as to search these instance products.

## Steps to reproduce the issue

1. Login into demo-oms instance of inventory count app
2. Search for product 
3. Logout from demo-oms from setting page
4. Now login into dev-hc 
5. In the search tab still the same product is visible

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by ymaheshwari1** [comment] 2022-12-13 13:36
Duplicate of #105

**Closed** 2023-02-03 09:13 UTC
Labels: bug
