### ISSUE TITLE
Search bar and product list should be cleared after logout

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/inventory-count#105] opened 2022-10-13 11:26 UTC
## Current behavior

After logout and then login again, the search bar field is pre-filled and the search results are visible

## Expected behavior

After logout and then login again, then all the previous search query and result should be cleared. 

## Steps to reproduce the issue

- Login into the application
- Search for a keyword like `MH`, you will see products matching the results
- Logout from the app and login again.
- See that the previous searched keyword and search results are still visible.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by dt2patel** [comment] 2023-01-17 09:36
closing task, duplicate of linked task

**Closed by dt2patel** 2023-01-17 09:36 UTC
Labels: bug
