### ISSUE TITLE
Remove Pointer on Hover from the Chips on Upload Page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/inventory-count#208] opened 2023-10-09 05:10 UTC
## Current behavior
In our current user interface on the Upload page, the chips (interactive elements used for tagging or categorization) have a pointer cursor when hovered over. However, this might confuse users as chips usually indicate non-interactive elements. 

## Expected behavior
To maintain a consistent and intuitive user experience, we need to remove the pointer cursor from the chips on the Upload page.

## Steps to reproduce the issue

- Open inventory count app
- Search for some keyword, like `wh`
- Select any product by clicking on the item and enter a stock on the details page and click save
- Now go to the upload page
- Hover over the chips `color` and `size` inside the card, as there is no action associated with those chips, pointer cursor is not required thus need to remove the pointer on hover.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by uuc110** [comment] 2023-10-13 05:19
Can you assign this issue to me

**Comment by Killer2OP** [comment] 2023-10-13 05:19
@Dhiraj1405 Can you assign me this issue.

**Comment by Dhiraj1405** [comment] 2023-10-13 05:21
> Can you assign this issue to me

Sure, go ahead.

**Comment by Dhiraj1405** [comment] 2023-10-13 05:22
> @Dhiraj1405 Can you assign me this issue.

Please pick another issue, had to assign it to @uuc110

**Comment by uuc110** [comment] 2023-10-13 18:59
Hey I'm working on this. Since couldn't finish it there due to some issue in node. can you provide me sample login for the app?

**Comment by ymaheshwari1** [comment] 2023-10-14 04:38
> Hey I'm working on this. Since couldn't finish it there due to some issue in node. can you provide me sample login for the app?

Hi, You can find the sample login details on our discord hacktoberfest channel.

**Comment by ymaheshwari1** [comment] 2023-10-14 16:19
Hi,

The issue is about removing the pointer event from the chips, that gets displayed inside the card. Currently, when hovering over the `color` or `size` chip we get a pointer but as those chips does not trigger any action so we need to remove the pointer cursor from those chips.

![image](https://github.com/hotwax/inventory-count/assets/41404838/26ac4336-489b-464f-84b1-c893df4bf303)

We don't need to change anything on the button.

Please update the PR. I will update the issue description with steps to reproduce.

**Comment by ymaheshwari1** [comment] 2024-07-18 05:44
Closing as inventory-count app is revamped and thus this issue is no more relevant

**Closed by ymaheshwari1** 2024-07-18 05:44 UTC
Labels: bug, hacktoberfest
